name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - api-gateway/**
      - todo-service/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api-gateway, todo-service]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Check for changes in directory
      id: check_changes
      run: |
        if git diff --name-only HEAD~1 HEAD | grep -q "^${{ matrix.service }}/"; then
          echo "changes=true" >> $GITHUB_ENV
        else
          echo "changes=false" >> $GITHUB_ENV
        fi

    - name: Build and push image
      if: env.changes == 'true'
      uses: docker/build-push-action@v4
      with:
        context: ./${{ matrix.service }}
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest
